---
- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/containerd.conf"
    mode: 0644
    state: "touch"
  become: true

- name: Add conf for containerd modules
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter
  become: true

- name: modprobe overlay
  command: modprobe overlay
  become: true

- name: modprobe br_netfilter
  command: modprobe br_netfilter
  become: true

- name: Create k8s cri config file
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    mode: 0644
    state: touch
  become: true

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    mode: 0644
    state: present
    block: |
           net.bridge.bridge-nf-call-iptables = 1
           net.ipv4.ip_forward = 1
           net.bridge.bridge-nf-call-ip6tables = 1
  become: true
  notify:
    - "Apply systemctl settings"

