---
# tasks file for roles/helm
- name: Install Helm
  import_tasks: helm-Install.yml
  when: inventory_hostname in groups["k8sMaster"]
  tags:
    - helm-Install
    - helm
    - all
    - never

- name: Configure Helm
  import_tasks: helm-Configure.yml
  when: inventory_hostname in groups["k8sMaster"]
  tags:
    - helm-Configure
    - helm
    - all
    - never
