---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name | quote }}
  name: {{ .Chart.Name | quote }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
    spec:
      containers:
      - image: "{{ .Values.global.image_repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name | quote }}
        ports:
        - containerPort: 10000  
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.image.port }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.resources}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
        restartPolicy: Always
