---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.image.port }}
      nodeport: 31420
      protocol: TCP
