---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catfact
  name: catfact
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catfact
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: catfact
    spec:
      containers:
      - image: techdufus/livestream-test:live
        name: catfact
        ports:
        - containerPort: 10000  
        readinessProbe:
          httpGet:
            path: /
            port: 10000
