---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: traefik-system
  labels:
    app: {{ .Chart.Name | quote }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }} 
    spec:
      serviceAccountName: {{ .Chart.Name | quote }} 
      containers:
      - image: traefik:2.4.5
        imagePullPolicy: IfNotPresent
        name: {{ .Chart.Name | quote }} 
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            memory: 50Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 500m
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
        volumeMounts:
        - mountPath: /acme
          name: acme
        - mountPath: /etc/{{ .Chart.Name }}/traefik.yml
          name: config-static
          subPath: traefik.yml
      volumes:
      - name: acme
        persistentVolumeClaim:
          claimName: "nfs-{{ .Chart.Name }}"
      - name: config-static
        configMap:
          name: "{{ .Chart.Name }}-static"
