---
# tasks file for roles/cleanup
- name: Clean apt cache
  apt:
    clean: true
  when: ansible_os_family == 'Debian'

- name: Ensure Docker is running (for pruning)
  service:
    name: docker
    state: started

- name: Prune Docker artifacts
  command: docker system prune --volumes --force

